FROM ros:noetic-ros-base-focal

RUN apt install -y python3-pip git qttools5-dev
RUN pip install -r requirements.txt
RUN source /opt/ros/noetic/setup.bash

# Download ROS packages
RUN mkdir ~/catkin_ws/src
WORKDIR ~/catkin_ws/src

# Install ROS dependencies
WORKDIR ~/catkin_ws/
RUN rosdep install --from-paths src --ignore-src -y

# Build ROS packages
RUN catkin_make --cmake-args -DCMAKE_BUILD_TYPE=Release

# Source the new packages
RUN source ~/catkin_ws/devel/setup.bash