services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: ros:noetic-ros-base-focal
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock

  ros:
    build: .
    command: tail -f /dev/null
    volumes: 
      - ./workspace:/root/catkin_ws/
    environment:
      - DISPLAY=novnc:0.0
    env_file:
      - ros.env
    networks:
      - x11
      
  novnc:  
    image: theasp/novnc:latest
    env_file:
      - novnc.env
    ports:
      - "8080:8080"
    networks:
      - x11
networks:
  x11: